# DO NOT CHANGE ANYTHING IN THIS WORKFLOW
# NO actions/checkout CODE CAN BE USED HERE TO RETAIN REPO SECURITY
name: PR Checklist & External Issue

on:
  pull_request_target:
    types: [opened]

jobs:
  checklist-and-issue:
    if: github.event.repository.name != 'Workshop_Template'
    uses: QLS-MiCM/MiCM_PR_Bot/.github/workflows/reusable_pr_check_issue_deploy.yml@main
    secrets: inherit
